nodes:
  bottom1: [-5, 0, 0]
  bottom2: [5, 0, 0]
  bottom3: [0, 0, 9]
  top1: [-5, 5, 0]
  top2: [5, 5, 0]
  top3: [0, 5, 9]
pair_groups:
  rod:
    - [bottom1, top2]
    - [bottom2, top3]
    - [bottom3, top1]
  string:
    - [bottom1, bottom2]
    - [bottom2, bottom3]
    - [bottom1, bottom3]
    - [top1, top2]
    - [top2, top3]
    - [top1, top3]
    - [bottom1, top1]
    - [bottom2, top2]
    - [bottom3, top3]
builders:
  rod:
    class: tgRodInfo
    parameters:
      density: 1
      radius: 1
  string:
    class: tgBasicActuatorInfo
    parameters:
      stiffness: 1000
      damping: 10
      pretension: 1000
